### ISSUE TITLE
Pincode checker not appearing at the cart

### ISSUE THREAD

**Issue by cmody** [netham91/Shopify-Zip-Check#1]
Hi

I have used the script as you have mentioned but the pincode checker does not appear on the on the page anywhere. Please let me know what to do.
<img width="1280" alt="screen shot 2016-05-24 at 2 00 54 pm" src="https://cloud.githubusercontent.com/assets/19532219/15497428/56a8de9c-21b8-11e6-9134-8c169c98b1a0.png">
<img width="1280" alt="screen shot 2016-05-24 at 2 00 47 pm" src="https://cloud.githubusercontent.com/assets/19532219/15497427/56a8cbd2-21b8-11e6-9666-21c0b2a3976e.png">
<img width="1280" alt="screen shot 2016-05-24 at 2 04 27 pm" src="https://cloud.githubusercontent.com/assets/19532219/15497452/7527f650-21b8-11e6-9be4-283c9660cc81.png">

**Comment by netham91** [comment]
Hi Cmody,

The COD checker appears on the cart page not the checkout. Many have requested this feature but unfortunately, the checkout page of Shopify cannot be accessed/modified by code and I believe it's primarily due to security reasons.

Check your cart page and you will find it there at the bottom.

**Comment by cmody** [comment]
Dear Hemant 

Thank you so much for your prompt responses. 

I really do appreciate it and I have it working now. The issue I was facing was that I am using the brooklyn theme and it has a cart option in the header. If I click that the pin code check does not appear. Is there anyway to add it there too ?

However if I go through the normal process of going to checkout the checker works perfectly.

Images are attached for your reference.

**Comment by 9044** [comment]
hey Hi is it possible to change  width of the search bar ?

Thank you

**Comment by cmody** [comment]
I am not too sure where should I look for the same.

**Comment by netham91** [comment]
@9044 Sure that can be done. I would request you to open a new issue, so that we can take the discussion there.

**Comment by netham91** [comment]
@cmody Great It worked for you. For the feature you are requesting I believe it can be done, but I cannot say it with 100% surety without looking at your theme's code.
