### ISSUE TITLE
cannot get it to function

### ISSUE THREAD

**Issue by dhealthsavor** [netham91/Shopify-Zip-Check#2]
![githubzipcheck](https://cloud.githubusercontent.com/assets/23509341/20366346/a42bd670-ac18-11e6-9262-7f1c468e34b9.JPG)

It displays on my cart page - the button just doesn't do anything no matter what you enter

please help

**Comment by netham91** [comment]
Sorry for late reply, drop me an email on netham91@gmail.com with your code and theme you are using. Also sometimes there are minor theme based issues.
